### ISSUE TITLE
Varying height slides seems broken

### ISSUE THREAD

**Issue by moimael** [FormidableLabs/nuka-carousel#172]
Hi,

When you have a look at the demo, or even by looking at the code, it seems that the sliderHeight is never actually applied to slides. How is this feature supposed to work ?

Thanks !

**Comment by GalynaBatig** [comment]
Hi,
It would be great to have this issue fixed. When my carousel is rendered, ul class="slider-list" has height: 0px;  and I can do nothing to make images visible. Please :)
Thanks!

**Comment by GusRuss89** [comment]
Not sure if you guys have the same issue as I had, but my slides are different heights and the whole slider was only looking at the height of the first slide - making the other slides get cut-off in some situations.

I noticed that the npm version is not up-to-date with Github, so I just updated my package.json dependency to be

`"nuka-carousel": "FormidableLabs/nuka-carousel",`

as per http://stackoverflow.com/a/23348036/1466282 and that fixed the issue for me (after restarting webpack).

**Comment by moimael** [comment]
Thanks for the tip @GusRuss89, but even with latest git code, the issue is still here.

**Comment by AndreasKlein** [comment]
Just FYI everyone: We were observing the same problem, but after tracking it down we realized it only occurs when an image take longer to load, so when it is not cached. Then `setDimensions` is not fired any more and the height of `<ul class="slider-list" />` remains `0px`. We fixed it for now by calling `setDimensions` in our code, when `onLoad` of the image fires.

**Comment by GalynaBatig** [comment]
Thank you, @AndreasKlein. Issue reason is the same for me. That is great that workaround is possible, though I hope issue will be fixed :)

**Comment by moimael** [comment]
Our issue still seems to stand, the height of the carousel is always the height of the first slide, not 0px.

**Comment by Marcsimm** [comment]
How do i call setDimensions manually?

**Comment by moimael** [comment]
I tried and it doesn't help. Digging a bit more into the issue, it seems to come from here:
```javascript
  getSlideStyles(index, positionValue) {
    var targetPosition = this.getSlideTargetPosition(index, positionValue);
    return {
      position: 'absolute',
      left: this.props.vertical ? 0 : targetPosition,
      top: this.props.vertical ? targetPosition : 0,
      display: this.props.vertical ? 'block' : 'inline-block',
      listStyleType: 'none',
      verticalAlign: 'top',
      width: this.props.vertical ? '100%' : this.state.slideWidth,
      height: 'auto',
      boxSizing: 'border-box',
      MozBoxSizing: 'border-box',
      marginLeft: this.props.vertical ? 'auto' : this.props.cellSpacing / 2,
      marginRight: this.props.vertical ? 'auto' : this.props.cellSpacing / 2,
      marginTop: this.props.vertical ? this.props.cellSpacing / 2 : 'auto',
      marginBottom: this.props.vertical ? this.props.cellSpacing / 2 : 'auto'
    }
  },
```

So basically the carousel (ul tag) has the right size (the size of the tallest slide), but since each child is wrapped into a li tag, it has this getSlideStyles applied, which set height to `auto`. If you set height to `100%` so the slide actually take the height of the carousel, it seems to fix the issue.

**Comment by moimael** [comment]
Is it me or master seems to have lost a lot of commits ? heightMode is no more here and I cannot find a lot of merged pull request in master anymore.

**Comment by kenwheeler** [comment]
yeah it did, I need to add them back in. I had to force revert because a couple of the commits were causing big problems for a large website.

**Comment by adamduncan** [comment]
Do you have a rough estimate when these props/features might find their way back in, and be published to npm? Thanks

**Comment by ryan-roemer** [comment]
Is this still an issue on `nuka-carousel@3.1.0+` now that we've landed https://github.com/FormidableLabs/nuka-carousel/pull/291?

**Comment by Pruxis** [comment]
Yes I still have this issue even on 3.2.0, that it's only updating the ul height when I change the height of the first slide.

**Comment by ryan-roemer** [comment]
Is it an issue on `nuka-carousel@4.1.0`?

**Comment by dfagan2** [comment]
@ashika01 - I'm still seeing this issue on v4.5.4. I also commented on https://github.com/FormidableLabs/nuka-carousel/issues/317

Example:
<img width="1312" alt="Screen Shot 2019-04-26 at 12 37 55 PM" src="https://user-images.githubusercontent.com/769972/56822900-7c96a380-6820-11e9-8604-7dadbec8b456.png">

Tinkering with height settings in CSS throws off all the height calculations of the whole carousel (either renders a few pixels tall, or way _too_ tall. 

That height of 'auto' seems to be the culprit. (The inline styles of this plugin are proving problematic in multiple spots.)
